import type { Metadata } from "next";
import OzoneClient from "@/components/pages/OzoneClient";

// Helper recommended pattern: sanitize JSON-LD to mitigate XSS vectors.
const safeJsonLd = (obj: unknown) => JSON.stringify(obj).replace(/</g, "\\u003c");

export const metadata: Metadata = {
  title: {
    absolute: "Ozone Therapy Hampstead & London | Healing-PRP Clinics",
  },

  description:
    "Doctor-led ozone therapy in Hampstead, London, including ozone blood therapy (MAH), rectal, vaginal and sinus ozone treatment following clinical assessment.",

  alternates: {
    canonical: "https://www.healing-prp.co.uk/hampstead/ozone-therapy",
  },

  openGraph: {
    title: "Ozone Therapy Hampstead & London | Healing-PRP Clinics",
    description:
      "Doctor-led ozone therapy in Hampstead, London, including ozone blood therapy (MAH), rectal, vaginal and sinus ozone treatment following clinical assessment.",
    url: "https://www.healing-prp.co.uk/hampstead/ozone-therapy",
    siteName: "Healing-PRP Clinics",
    locale: "en_GB",
    type: "website",
    images: [
      {
        url: "/hero_img.png",
        width: 1200,
        height: 630,
        alt: "Medical Ozone Therapy in Hampstead, London",
      },
    ],
  },

  twitter: {
    card: "summary_large_image",
    title: "Ozone Therapy Hampstead & London | Healing-PRP Clinics",
    description:
      "Doctor-led ozone therapy in Hampstead including ozone blood therapy, rectal, vaginal and sinus ozone treatments.",
    images: ["/hero_img.png"],
  },
};

// --- SEO RICH FAQS ---
const faqs = [
  {
    question: "Is ozone autohaemotherapy the same as IV ozone therapy?",
    answer: "The term 'IV ozone therapy' is sometimes used online to describe ozone blood treatments. In major ozone autohaemotherapy, ozone gas is not injected directly into a vein. A measured amount of blood is withdrawn into a closed system, treated with a controlled oxygen-ozone mixture outside the body, and then returned to the circulation.",
  },
  {
    question: "Is ozone therapy the same as oxygen therapy?",
    answer: "No. While they both involve oxygen, medical ozone therapy uses a highly specific mixture of pure oxygen (O2) and ozone (O3) generated by a specialised medical device.",
  },
  {
    question: "How many ozone treatments will I need?",
    answer: "This varies considerably depending on the treatment route, your specific condition, and your individual response to the therapy. We do not prescribe a fixed, universal course of treatment for every patient.",
  },
  {
    question: "Is ozone therapy painful?",
    answer: "Comfort levels depend on the route of administration. Rectal and vaginal insufflation are generally painless. Major Autohaemotherapy (MAH) involves a standard needle insertion, similar to a routine blood test. We take every step to ensure your comfort during the procedure.",
  },
  {
    question: "Can ozone therapy replace my existing medication?",
    answer: "No. Ozone therapy is an adjunctive treatment. Patients should never stop prescribed medication or specialist care unless explicitly advised to do so by their treating clinician or GP.",
  },
  {
    question: "How do I know which type of ozone therapy I need?",
    answer: "The most appropriate route of administration is decided collaboratively following a thorough clinical assessment of your medical history and current symptoms.",
  },
];

// --- UPGRADED JSON-LD SCHEMA: Medical Clinic, Therapy & Doctor ---
const ozoneSchema = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "MedicalClinic",
      "@id": "https://www.healing-prp.co.uk/hampstead/ozone-therapy#clinic",
      "name": "Healing-PRP Clinics Hampstead",
      "description": "Doctor-led medical clinic in Hampstead, London offering medical ozone therapy following clinical assessment.",
      "telephone": "+44 7990 364147",
      "address": {
        "@type": "PostalAddress",
        "streetAddress": "2 Hampstead High St",
        "addressLocality": "London",
        "addressRegion": "Greater London",
        "postalCode": "NW3 1PR",
        "addressCountry": "GB"
      },
      "areaServed": [
        "Hampstead",
        "North London",
        "North West London",
        "Belsize Park",
        "West Hampstead",
        "Highgate",
        "London"
      ],
      "availableService": [
        { "@id": "https://www.healing-prp.co.uk/hampstead/ozone-therapy#therapy" }
      ],
      "employee": [
        { "@id": "https://www.healing-prp.co.uk/hampstead/ozone-therapy#dr" }
      ]
    },
    {
      "@type": "Person",
      "@id": "https://www.healing-prp.co.uk/hampstead/ozone-therapy#dr",
      "name": "Dr Syed Abdi",
      "jobTitle": "Medical Director",
      "telephone": "+44 7990 364147",
      "url": "https://www.healing-prp.co.uk/our-doctor",
      "identifier": {
        "@type": "PropertyValue",
        "propertyID": "GMC Reference Number",
        "value": "6083294"
      },
      "sameAs": [
        "https://www.gmc-uk.org/registrants/6083294"
      ],
      "worksFor": {
        "@id": "https://www.healing-prp.co.uk/hampstead/ozone-therapy#clinic"
      }
    },
    {
      "@type": "MedicalTherapy",
      "@id": "https://www.healing-prp.co.uk/hampstead/ozone-therapy#therapy",
      "name": "Medical Ozone Therapy",
      "alternateName": "Ozone Therapy",
      "url": "https://www.healing-prp.co.uk/hampstead/ozone-therapy",
      "description":
        "Doctor-led medical ozone therapy in Hampstead, London, including major ozone autohaemotherapy, rectal ozone therapy, vaginal ozone therapy and local sinus ozone therapy following clinical assessment."
    }
  ]
};

// --- BREADCRUMB SCHEMA ---
const breadcrumbSchema = {
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [
    {
      "@type": "ListItem",
      "position": 1,
      "name": "Home",
      "item": "https://www.healing-prp.co.uk/"
    },
    {
      "@type": "ListItem",
      "position": 2,
      "name": "Hampstead Clinic",
      "item": "https://www.healing-prp.co.uk/hampstead"
    },
    {
      "@type": "ListItem",
      "position": 3,
      "name": "Medical Ozone Therapy",
      "item": "https://www.healing-prp.co.uk/hampstead/ozone-therapy"
    }
  ]
};

export default function HampsteadOzoneTherapyPage() {
  // --- GENERATE JSON-LD SCHEMA FOR FAQS ---
  const faqSchema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    "mainEntity": faqs.map((faq) => ({
      "@type": "Question",
      "name": faq.question,
      "acceptedAnswer": {
        "@type": "Answer",
        "text": faq.answer,
      },
    })),
  };

  return (
    <main>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: safeJsonLd(ozoneSchema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: safeJsonLd(breadcrumbSchema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: safeJsonLd(faqSchema) }}
      />
      
      <OzoneClient 
        locationName="Hampstead, London"
        servingAreas="North London • Belsize Park • West Hampstead • Highgate"
        faqs={faqs}
      />
    </main>
  );
}
